### ISSUE TITLE
Build Faild

### ISSUE THREAD

**Issue by cskasun** [yimankaing/react-native-bluetooth-printer#3]
When I going to build/ run this project getting errors like following.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.io.FileNotFoundException: /Users/h2e/Desktop/mis/printer/MyPrinter#3/libs/printerlibs.jar (No such file or directory)

**Comment by yimankaing** [comment]
oh i'm sorry for not exclude that file. I've fixed.
