### ISSUE TITLE
Will this work with any thermal receipt printer?

### ISSUE THREAD

**Issue by arpitjain-in** [yimankaing/react-native-bluetooth-printer#4]
Hi ,
i'm developing one PoS system and there I need to connect printer with thermal printer.
Will this work with any thermal receipt printer?

Thanks

**Comment by fabiobtaaa** [comment]
Hi, @arpitjain-in did you find any solution? thanks in advance.

**Comment by yimankaing** [comment]
I think it will work all using Bluetooth
