### ISSUE TITLE
Become Contributor

### ISSUE THREAD

**Issue by aldente05** [yimankaing/react-native-bluetooth-printer#6]
how to become a contributor for this repo. @yimankaing

**Comment by yimankaing** [comment]
Would you like to become contributor. I stop maintaining this repository. I currently use flutter instead.

**Comment by aldente05** [comment]
yes, i want to maintain this library. could u give me an access for pull request?

**Comment by yimankaing** [comment]
i'm sorry for late reply. Thanks! you're now able to access for pull request.
