### ISSUE TITLE
This code doesn't work on my machine.

### ISSUE THREAD

**Issue by bklutse20** [yimankaing/react-native-bluetooth-printer#7]
I am unable to run the code in debug after running npm install and react-native run-android it returns an error message.

**Comment by yimankaing** [comment]
what is the error?

**Comment by bklutse20** [comment]
I get this error anytime I run 'react-native run-android'

FAILURE: Build failed with an exception.

* Where:
Build file '/Applications/MAMP/htdocs/react_native_project/printer/node_modules/react-native-fs/android/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':react-native-fs'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by bklutse20** [comment]
Is there any update to this repository that is tested and working that I can use please. I badly need this for a project. @yimankaing  kindly help

**Comment by bklutse20** [comment]
I have been trying hard to resolve this and I now settle on this error @yimankaing @aldente05 

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

**Comment by bklutse20** [comment]
Thank you all. Had to do some updates on my gradle. Much respect for your time @yimankaing
